image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

environment:
  access_token:
    secure: hTA0J7I0WY9N0G3IB4D9AaukIGWBtVIMC8eheX/KCx3fOSM+wz3I6gZTCpYq61oT

install:
  - ps: Install-Product node 10 x64
  - yarn

build: off

build_script: 
  - yarn build
  - npm run publish
  
