image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

environment:
  access_token:
    secure: KEHM+BZr+Jp5MFlY6gzPAaLjtJU0Nfu+77DlcAWj526xtWrS5uePFv/UsiYn9eT8

install:
  - ps: Install-Product node 10 x64
  - yarn

build: off

build_script: 
  - yarn build
  - npm run publish
  - npm run publish-32
  