image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

environment:
  access_token:
    secure: 665a146770bc19105fe9804257e1cd29b3911343

install:
  - ps: Install-Product node 10 x64
  - yarn

build: off

build_script: 
  - yarn build
  - npm run publish
  
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "609028727@qq.com"
  - git config --global user.name "WuLittleRui"
  - git commit ...
  - git push ...