image: Visual Studio 2017
platform: x64

environment:
  access_token:
    secure: 5yCTrYZ1Hp12lMi1SDDeLBXNYTgnvlnVMLXprW1uQRobj+UHMgK2yT9nGACG9DgT

install:
  - ps: Install-Product node 10 x64
  - yarn

build: off

build_script: 
  - yarn build
  - npm run publish
  