image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

environment:
  access_token:
    secure: 55d9df4e0ece6277477667c81e672e7703236bcc

install:
  - ps: Install-Product node 10 x64
  - yarn

build: off

build_script: 
  - yarn build
  - npm run publish
  