image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

environment:
  access_token:
    secure: 665a146770bc19105fe9804257e1cd29b3911343

install:
  - ps: Install-Product node 10 x64
  - yarn

build: off

build_script: 
  - yarn build
  - npm run publish